### ISSUE TITLE
Can't build for iOS Simulator on v1.0.2+

### ISSUE THREAD

**Issue by rpekarek-tc** [newrelic/newrelic-flutter-agent#39]
After upgrading from `newrelic_mobile: 1.0.1` to 1.0.2 or  1.0.3 I'm no longer able to build our app on the iOS simulator. Version 1.0.1 and below work as expected. The following error is thrown:

```
Failed to build iOS app
Error output from Xcode build:
↳
    2023-07-26 17:05:18.207 xcodebuild[85265:514413] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
```

**Comment by ndesai-newrelic** [comment]
@rpekarek-tc can you check this? https://stackoverflow.com/questions/75902251/flutter-ios-build-failed-dvtcoredeviceenabledstate-disabled

**Comment by rpekarek-tc** [comment]
Hey @ndesai-newrelic, we have the debug configuration set and `-f` in our readLink command. Our application runs fine with new_relic: 1.0.1. This only happens when we upgrade to 1.0.2 or 1.0.3

**Comment by ndesai-newrelic** [comment]
please provide your Xcode Version, Dart Version and Flutter Version Information.

**Comment by rpekarek-tc** [comment]
```
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-arm64,
    locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.80.1)
[✓] Connected device (3 available)
[✓] Network resources
```

**Comment by ndesai-newrelic** [comment]
@rpekarek-tc  can you share your pubspec.yaml file? i am unable to reproduce on my example app. can you also try to build app without newrelic plugin?

**Comment by rpekarek-tc** [comment]
Confirmed app builds without the new_relic plugin (after deleting associated code)

```
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1000

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: "3.10.6" # update build.yml when updating this value

dependencies:
  add_2_calendar: ^2.1.3
  android_path_provider:
    git:
      url: https://github.com/zezo357/android_path_provider_v2.git
      ref: 27affdb30500162f811f9adaefdc3dc1d67ced27
  animations: ^2.0.3
  any_link_preview: ^2.0.9
  auto_size_text: ^3.0.0
  badges: ^2.0.0-nullsafety.1
  braze_plugin: ^4.1.0
  cached_network_image: ^3.2.3
  chewie: 1.3.0
  clipboard: ^0.1.3
  connectivity_plus: ^2.3.6
  defer_pointer: ^0.0.2
  device_info_plus: ^4.1.3
  dio: ^5.0.3
  dotted_border: ^2.0.0+1
  duration: 3.0.11
  encrypt: ^5.0.1
  equatable: ^2.0.0
  expandable_text: ^2.2.0
  file_picker: ^5.2.0+1
  # Locked firebase_core_platform_interface to version 4.5.1 to avoid error
  # https://github.com/firebase/flutterfire/issues/9806
  firebase_core_platform_interface: 4.5.1
  firebase_crashlytics: ^2.8.2
  firebase_dynamic_links: ^4.1.3
  firebase_messaging: ^11.2.13
  flutter:
    sdk: flutter
  flutter_apns: ^1.5.4
  flutter_app_badger: ^1.3.0
  flutter_cache_manager: ^3.1.2
  flutter_config: ^2.0.0
  flutter_html: 3.0.0-alpha.5
  flutter_inappwebview: 6.0.0-beta.24+1
  flutter_keyboard_visibility: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.9+1
  flutter_oss_licenses: ^1.1.1
  flutter_secure_storage: ^6.0.0
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  flutter_svg: ^1.1.3
  flutter_typeahead: ^4.1.1
  geolocator: ^9.0.2
  get: ^4.6.5
  gettext_parser: ^0.2.0
  google_maps_cluster_manager: ^3.0.0+1
  google_maps_flutter: ^2.2.3
  google_maps_webservice: ^0.0.20-nullsafety.2
  graphql_flutter: ^5.1.1-beta.4
  i18n_extension: ^9.0.0
  image: ^3.0.2
  image_picker: ^0.8.5+3
  inview_notifier_list: ^3.0.0
  json_cache: ^1.3.1
  jwt_decoder: ^2.0.1
  local_auth: ^2.1.6
  lottie: ^1.3.0
  mime: ^1.0.2
  mixpanel_flutter: ^2.1.1
  newrelic_mobile: 0.0.1
  notification_permissions: ^0.6.0
  okta:
    path: components/okta
  open_filex: ^4.1.1
  package_info: ^2.0.2
  path: ^1.7.0
  path_provider: ^2.0.1
  pdfx: ^2.2.0
  percent_indicator: ^4.2.2
  permission_handler: ^10.0.0
  phone_numbers_parser: ^3.0.2
  popover: ^0.2.1
  printing: ^5.8.0
  quick_actions: ^1.0.5
  rx_shared_preferences: ^3.0.0
  rxdart: ^0.27.7
  rxdart_ext: ^0.2.8
  safe_device: ^1.1.4
  sanitize_html: ^2.0.0
  scrollable_positioned_list: ^0.3.2
  share_plus: ^4.0.8
  shared_preferences: ^2.0.5
  shimmer: ^2.0.0-nullsafety.0
  sticky_headers: ^0.3.0+2
  string_validator: ^0.3.0
  timezone: ^0.8.0
  # Fixes null initialLink on iOS: https://github.com/avioli/uni_links/pull/129
  uni_links:
    git:
      url: https://github.com/ritaamro/uni_links
      path: uni_links
  url_launcher: ^6.1.10
  video_player: ^2.2.5
  visibility_detector: ^0.3.3
  webview_flutter: ^2.0.2

# Remove once we're ready to upgrade to flutter_inappwebview: ^6.X (in beta)
dependency_overrides:
  url_launcher_android: 6.0.35

dev_dependencies:
  dart_code_metrics: ^5.7.3
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.2.2
  integration_test:
    sdk: flutter
  lint: ^2.1.2
  mocktail: ^0.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/ca/
    - assets/data/json/
    - assets/data/json/localization/
    - assets/icons/
    - assets/iconsDark/
    - assets/icons/map/
    - assets/icons/universal/
    - assets/icons/ellipse/
    - assets/images/

  fonts:
    - family: Iconsax
      fonts:
        - asset: assets/fonts/appIcons/iconsax.ttf
    - family: IconsaxBold
      fonts:
        - asset: assets/fonts/appIcons/iconsax-bold.ttf
    - family: Outfit
      fonts:
        - asset: assets/fonts/outfit/Outfit-400.ttf
          weight: 400
        - asset: assets/fonts/outfit/Outfit-500.ttf
          weight: 500
        - asset: assets/fonts/outfit/Outfit-700.ttf
          weight: 700
```
